# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Stars from Rigby
email: jason@thought.net
name: Jason L. Wright
description: > # this means to ignore newlines until "baseurl:"
  Kernel developer, astronomer, father, radio operator.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wrigjl.github.io" # the base hostname & protocol for your site
twitter_username: risenrigel
github_username:  wrigjl

# Build settings
markdown: kramdown
